#!bin/bash
clear


echo "════════════════════════ "
echo "Author : AhmadGans "
echo "Team: InfectSec security "
echo "════════════════════════ "
figlet Spam-Call 
echo '
[1], Spam Call
[2], Exit Tools                                            '

echo
read -p "Masukan Pilihan Anda : " pil
if [[ $pil == 1 ]]; then
read -p "Masukan No Target Contoh 895397094109 : " nomor
link="https://id.jagreward.com/member/verify-mobile/$nomor"
curl -s $link
else
echo "Trima Kasih Sudah Menggunakan Tools ini"
exit
fi
echo
